// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhvtpfrzlxgyiienlbuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodnRwZnJ6bHhneWlpZW5sYnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTE4ODYsImV4cCI6MjA3MTI4Nzg4Nn0.6Qz9NyH7WqVuKsxoxr0LTi7hK1o0UxmQfC7cNc6S69s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});